use_frameworks!

platform :ios, '10.0'

target 'EbonyDependencyKit_Example' do
  pod 'EbonyDependencyKit', :path => '../'

  target 'EbonyDependencyKit_Tests' do
    inherit! :search_paths

    
  end
end
